config/routes.rb
Rails.application.routes.draw do

  # THE HOME CONTROLLER
  get "/home" => "home#index", as: :index
  get "/home/about" => "home#about", as: :about
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  # This will direct to the blog homepage
  root "home#index"


  # THE POSTS CONTROLLER
  resources :posts do
    resources :comments, only: [:index, :create, :destroy]
    resources :favorites, only: [:create, :destroy]
  end

  resources :favorites, only: [:index]

  # THE USERS CONTROLLER
  resources :users, only: [:new, :create, :edit, :update, :show]
  get "/users/edit_password/:id" => "users#edit_password",  as: :edit_password
  patch "/users/edit_password/:id" => "users#update_password"

  # THE SESSIONS CONTROLLER
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :user_id, :post_id, presence: true
  validates :user_id, uniqueness: {scope: :post_id}
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  before_action :authenticate_user

  def index
    # This will get all the posts that the user has favorited
    @favorite = current_user.favorited_posts
  end

  def create
    @post = Post.find(params[:post_id])
    favorite = Favorite.new(post: @post, user: current_user)
    respond_to do |format|
      if favorite.save
        format.html { redirect_to @post, notice: "Favorited!" }
        # this will look for a favorited.js.erb file to render
        format.js { render :favorited }
      else
        format.html { redirect_to @post, alert: "Favorite not completed try again!"}
        # this will look for an unfavorited.js.erb file to render
        format.js { render :unfavorited }
      end
    end
  end

  def destroy
    favorite = current_user.favorites.find(params[:id])
    @post = Post.find(params[:post_id])
    favorite.destroy
    respond_to do |format|
      format.html {redirect_to @post, notice: "Un-favorited"}
      format.js { render }
    end
  end

end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_post_fav.html.erb
<% favourite = @post.favorite_for(current_user)  %>
<% if favourite %>
  <%= link_to fa_icon("thumbs-up"), post_favorite_path(@post, favourite),
                                      method: :delete,
                                      remote: true,
                                      class:"like-fav-icon"  %>
    <%# remote: true => it disables the rendering of a view it will just send the info via the format you tell it. See line format.js .... in the controller %>
<% else %>
  <%= link_to fa_icon("thumbs-o-up"), post_favorites_path(@post),
                                      method: :post,
                                      remote: true,
                                      class:"like-fav-icon" %>
<% end %>
  (<%= @post.favorites.count %>)

app/views/favorites/destroy.js.erb
// Here we just continue to render the post-fav partial as it takes care of all the logic for us already. If we were doing something like removing a comment or post we would have instructions for removing it from the html/page.
console.log("made it to the destroy.js");
$("#post-fav").html("<%= j render 'post_fav' %>");

app/views/favorites/favorited.js.erb
// This says target the post-fav id and place in the post-fav view
console.log("made it to the favorited.js")
$("#post-fav").html("<%= j render 'post_fav' %>")

app/views/favorites/index.html.erb
<div class="main-page">
  <h1>All Favourited Questions</h1>

  <table class="table table-striped">
    <% @favorite.each do |favorite| %>
      <tr>
        <td><%= link_to favorite.title, post_path(favorite) %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/favorites/unfavorited.js.erb
alert("Can't favourite, may have been favourited already!");
window.location.reload();