config/routes.rb
Rails.application.routes.draw do

  # THE HOME CONTROLLER
  get "/home" => "home#index", as: :index
  get "/home/about" => "home#about", as: :about
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  # This will direct to the blog homepage
  root "home#index"


  # THE POSTS CONTROLLER
  resources :posts do
    resources :comments, only: [:index, :create, :destroy]
    resources :favorites, only: [:create, :destroy]
  end

  resources :favorites, only: [:index]

  # THE USERS CONTROLLER
  resources :users, only: [:new, :create, :edit, :update, :show]
  get "/users/edit_password/:id" => "users#edit_password",  as: :edit_password
  patch "/users/edit_password/:id" => "users#update_password"

  # THE SESSIONS CONTROLLER
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  # The scope part validates that the body is unique per post. The same body
  # however may be used for multiple posts
  validates :body, presence: true, uniqueness: {scope: :post_id}

  def user_full_name
    user.full_name if user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :find_post, except: [:destroy]
  before_action :authenticate_user, except: [:index]

  # create an index action for the jQuery client
  def index
    render json: @post.comments
  end

  def create
    comment_params = params.require(:comment).permit(:body)
    @comment = Comment.new comment_params
    @comment.post = @post
    @comment.user = current_user
    respond_to do |format|
      if @comment.save
        CommentsMailer.notify_post_owner(@comment).deliver_later
        format.html { redirect_to post_path(@post), notice: "Comment successfully logged"}
        format.js { render :comment_created}
      else
        # this is actually a direct to the posts folder and looking for the show file
        # not actually a url posts_path
        format.html { render "/posts/show" }
        format.js { render :comment_failed }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    redirect_to root_path, alert: "ACCESS DENIED" unless can? :manage, @comment
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to post_path(params[:post_id]), notice: "Comment was deleted."}
      format.js { render :destroy }
    end
  end

  private

  def find_post
    @post = Post.friendly.find(params[:post_id])
  end
end

app/helpers/comments_helper.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id(comment) %>">
  <%= comment.body %> Created by: <%= comment.user_full_name %>
  on <%= comment.created_at.in_time_zone('Pacific Time (US & Canada)').strftime("%Y-%b-%d at %I:%M%p")%>
  <% if can? :destory, comment%>
    <%= link_to "Delete", post_comment_path(@post, comment),
                          method: :delete,
                          remote: true,
                          data: {confirm: "Are you sure?"} %>
  <% end %>
  <hr>
</div>

app/views/comments/_form.html.erb
<%= @comment.errors.full_messages.join(", ") %>
<%# This creates the comment box %>
<%# form_for [@post, @comment], remote: true do |f| %>
  <!-- <div> -->
    <%# f.label :comment %>
    <%# f.text_area :body %>
  <!-- </div> -->
  <%# f.submit  %>
<%# end %>

<%= simple_form_for [@post, @comment], remote: true do |f| %>
  <%= f.input :body, label: "Comment"%>
  <%= f.submit ({class: "btn btn-primary"}) %>
<% end %>

app/views/comments/comment_created.js.erb
$(".comments ul").prepend("<%= j render 'comment', comment: @comment  %>")

<%# we need this to reset the @comment and the comment body %>
<% @comment = Comment.new %>
$("#comment_body").val("");

app/views/comments/comment_failed.js.erb
$("#comment-form").html("<%= j render 'form' %>")

app/views/comments/destroy.js.erb
<%# Need to choose the comment that we are interested in deleting. Have it fadeout then eventually dissappear from the page %>
$("#<%= dom_id(@comment) %>").fadeOut(1000, function() {
  $(this).remove();
});

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<%= @comment.errors.full_messages.join(", ") %>
<%= form_for @comment do |f| %>
  <div>
    <%= f.label :comment %>
    <%= f.text_area :body %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/index.html.erb
<h1>View All Comments <%= @comments.count %></h1>

<%# Use the following code to create links to each individual blog post %>
<% @comments.each do |comment| %>
  <%# link_to is a rails method that takes in 4 parameters. The first
      two being display and path to direct to.%>
  <%= link_to comment.body, comment_path(comment)%>
  <hr>
<% end %>

app/views/comments/new.html.erb
<h1>Create a Comment</h1>
<%= @comment.errors.full_messages.join(", ") %>
<%= form_for @comment do |f| %>
  <div>
    <%= f.label :comment %>
    <%= f.text_area :body %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/show.html.erb
<p><%= @comment.body %></p>
<br>
<%= link_to "Edit Comment", edit_comment_path(@comment) %> |
<%= link_to "Delete Comment",
             comment_path(@comment),
             method: :delete,
             data: {confirm: "Are you sure you want to delete the comment?"} %>