config/routes.rb
Rails.application.routes.draw do

  # THE HOME CONTROLLER
  get "/home" => "home#index", as: :index
  get "/home/about" => "home#about", as: :about
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  # This will direct to the blog homepage
  root "home#index"


  # THE POSTS CONTROLLER
  resources :posts do
    resources :comments, only: [:index, :create, :destroy]
    resources :favorites, only: [:create, :destroy]
  end

  resources :favorites, only: [:index]

  # THE USERS CONTROLLER
  resources :users, only: [:new, :create, :edit, :update, :show]
  get "/users/edit_password/:id" => "users#edit_password",  as: :edit_password
  patch "/users/edit_password/:id" => "users#update_password"

  # THE SESSIONS CONTROLLER
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>

  <!-- Nav Bar  -->
  <nav class="navbar navbar-custom navbar-fixed-top">
    <div class="container" style="padding: 10px">
      <!-- This is for the lefthand side of the nav bar -->
      <a class="navbar-left" href="#"><%= image_tag "logo.png" %></a>
      <a class="navbar-brand navbar-left" href="#">An Awesome Blog</a>

      <!-- This is the righthand side of the nav bar -->
      <ul class="nav navbar-nav navbar-right">

        <li><%= link_to "Home", index_path %></li>
        <li><%= link_to "About Me", about_path %></li>

        <!-- Create a dropdown button for all the user options -->
        <li>
          <div class="dropdown">
          <span class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Posts<span class="caret"></span></span>
            <ul class="dropdown-menu">
              <li><%= link_to "See All Posts", posts_path %></li>
              <li><%= link_to "Create New Post", new_post_path %></li>
              <li><%= link_to "All Favorited Posts", favorites_path %></li>
            </ul>
          </div>
        </li>

        <!-- Create a dropdown button for all the user options -->
        <li>
          <div class="btn-group">
            <button type="button" class="btn btn-default btn-sm">
              <% if user_signed_in? %>
                Hi <%= current_user.first_name %>
              <% else %>
                Account
              <% end %>
            </button>
            <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="caret"></span>
              <span class="sr-only">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu">
              <li>
                <% if user_signed_in? %>
                  <!-- Welcome back <%= current_user.first_name %> -->
                  <%= link_to "Update Profile", user_path(current_user)%>
                  <%= link_to "Logout", sessions_path, method: :delete, data: {confirm: "Are you sure you want to log out?"} %>
                <% else %>
                  <%= link_to "Login", new_session_path%>
                  <%= link_to "Sign Up", new_user_path%>
                <% end %>
              </li>
            </ul>
          </div>
        </li>
      </ul>
    </div>
  </nav>

  <%= yield %>

  </body>
</html>